name: open_lakehouse
version: 1.0.0
config-version: 2

profile: open_lakehouse

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  open_lakehouse:
    +materialized: table
    staging:
      +schema: staging
    analytics:
      +schema: analytics

snapshots:
  open_lakehouse:
    +target_schema: snapshots
